charts/ubiquitous-journey/requirements.yaml, values-bootstrap.yaml
=> MOVE - jenkins agents and bump chart version to matchz 🙈

argo-app-of-apps.yaml
variable  name changed during merge
=> 🍿 fixup values naming 🍿

argo-app-of-apps.yaml, ubiquitous-journey/templates/argoapplicationdeploy.yaml, ubiquitous-journey/values-tooling.yaml
fix name 
Invalid value: "Labs-DevEx": a DNS-1123 subdomain must consist of lower case alphanumeric characters,
and merge argodeploy template so works without helm apps (crw)
=> Merge Fixes

README.md, ubiquitous-journey/values-tooling.yaml
=> 🐩 Readme updates and fix DESTIATION 🐩

README.md, bootstrap/templates/argocd-install.yaml, bootstrap/values-bootstrap.yaml
PR changes from @eformat 's  argocd stuff #83
=> 🦆  Minor tweaks to the Argo Deploy that mike created 🦆

bootstrap/values-bootstrap.yaml
do not merge yet
alternative namespace global values
matches with - https://github.com/rht-labs/helm-charts/pull/22
=> 🍿 WIP - Feature/namespace globals 🍿

ubiquitous-journey/values-tooling.yaml
Repo URL currently points to my fork of Wekan upstream. When my PR is merged, it can point to the upstream.
=> 🐊Wekan is added🐊

README.md, ubiquitous-journey/values-tooling.yaml
Wekan helm chart now has Route template so we can use the upstream one 🐬
=> Wekan is pointed to upstream repo

CODE_OF_CONDUCT.md, CONTRIBUTING.adoc
🧟‍♀️ Readme updates for #2  🧟‍♂️
=> 🧟‍♀️ Readme updates for #2 🧟‍♂️

README.md, argo-app-of-apps.yaml, force-delete-application-cr.sh, set-namespace.sh
=> 🐪 Fix/fixns multi-os 🐪

README.md, bootstrap/values-bootstrap.yaml
new version of argocd released
=> 🥚 bump argocd 1.5.2 🥚

ubiquitous-journey/values-tooling.yaml
add tekton/openshift pipelines, this is a cluster wide operator
see https://github.com/rht-labs/refactored-adventure/pull/3
=> 🛴 Feature/tekton 🛴

bootstrap/Chart.yaml, bootstrap/requirements.yaml, bootstrap/values-bootstrap.yaml
Needs to have https://github.com/rht-labs/helm-charts/pull/27 merged before this one.
Also need to test it! #YOLO
=> WIP - 👻 Move the ArgoCD Operator out of UJ 👻

bootstrap/Chart.yaml
switch to rht cop dex image
see - https://github.com/rht-labs/helm-charts/pull/29
=> ♻️Fix/dex ♻️

ubiquitous-journey/values-tooling.yaml
Currently, it uses my fork. When my PR is merged, I'll update it as upstream chart. 👩🏻‍🏫
=> 🦀 mattermost added 🦀

README.md, ubiquitous-journey/values-tooling.yaml
adding etherpad chart
https://github.com/rht-labs/ubiquitous-journey/issues/15
https://github.com/rht-labs/helm-charts/pull/31
=> 🥝 add etherpad chart 🥝

README.md, bootstrap-master/.helmignore, bootstrap-master/Chart.yaml, bootstrap-master/values-bootstrap.yaml, bootstrap/Chart.yaml
add a bootstrap-master chart for the master-child argocd demoing
fixup description and instructions
=> 🥧  more comprehensive bootstrap-master example 🥧

example-deployment/values-applications.yaml
@springdo -im just pushing this .. buscuits clearly not a tag in quay ;)
https://quay.io/repository/springdo/pet-battle?tag=latest&tab=tags
🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖🦖
=> 🛫 fixes  🛫

bootstrap-master/values-bootstrap.yaml, bootstrap/values-bootstrap.yaml
=> 🦟 argocd 1.5.4 🦟

README.md, bootstrap-master/Chart.yaml, bootstrap/Chart.yaml, ubiquitous-journey/values-tooling.yaml
Mattermost chart is updated. Also increased some of the chart versions 🚀
PS: sorry for my emojiless commit messages 😅
=> Pointing Mattermost upstream chart

bootstrap/Chart.yaml
see: 
https://github.com/rht-labs/helm-charts/issues/41
https://github.com/rht-labs/helm-charts/pull/45/
=> 🦐 bump argocd-operator 🦐

ubiquitous-journey/values-tooling.yaml
add owncloud now chart available
=> 🦄 merge owncloud 🦄

bootstrap-master/Chart.yaml, bootstrap/values-bootstrap.yaml
argocd 1.5.5
matches: https://github.com/rht-labs/helm-charts/pull/50
=> 🦆 bump versions 🦆

example-deployment/values-applications.yaml
override image as default values being overridden by pipeline build
=> 🦂 pet-battle-api image 🦂

ubiquitous-journey/values-tooling.yaml
=> 🦦 bump jenkins default chart  🦦

README.md, set-namespace.sh
and update README accordingly :)
=> Update set-namespace.sh script to add staging namespace

bootstrap-master/values-bootstrap.yaml, bootstrap/Chart.yaml, bootstrap/values-bootstrap.yaml
bump to latest argocd, tested deploy OK
aligns with:
https://github.com/rht-labs/helm-charts/pull/56
=> 🦩 Feature/argocd 1.6.0 🦩

ubiquitous-journey/values-tooling.yaml
Merge once this one has gone in .... https://github.com/rht-labs/helm-charts/pull/58
@ckavili @jtudelag
=> 😃 Bump Jenkins chart version 😃

README.md
Leaving oc create -f- may cause json unmarshalling problem while decoding template file.
Suggested use: oc create -f - (with a space)
=> Update oc create -f- parts

bootstrap-master/values-bootstrap.yaml, bootstrap/Chart.yaml, bootstrap/values-bootstrap.yaml
=> 🦘 bump argocd 1.6.1, operator 0.0.11 🦘

README.md, bootstrap/Chart.yaml, bootstrap/values-bootstrap.yaml
See: https://github.com/rht-labs/helm-charts/pull/68
adding namespace RBAC for ArgoCD service account
=> 🦃 rbac for argocd bootstrap 🦃

ubiquitous-journey/values-tooling.yaml
fixes for latest tekton preview. put subscription in correct namespace
https://github.com/rht-labs/refactored-adventure/pull/7
=> 🐪 tekton latest preview release 🐪

README.md, example-deployment/templates/argoapplicationdeploy.yaml, example-deployment/values-applications.yaml, ubiquitous-journey/templates/argoapplicationdeploy.yaml, ubiquitous-journey/values-tooling.yaml
I tried to tidy up `values-tooling.yaml` and move some related content into app definitions instead of using the anchor to make it more readable. 
Also, I corrected a minor difference in argo app definition chart between `tooling` and `example app`, and updated `README`.
=> Tidied up the values tooling

README.md, argo-app-of-apps.yaml, bootstrap/values-bootstrap.yaml, ubiquitous-journey/values-day2ops.yaml
We introduced day 2 operations with a separated values file! (Current it points to my fork due to https://github.com/redhat-cop/openshift-management/pull/74.)
=> 📓 day2ops added  📓

bootstrap-master/values-bootstrap.yaml, bootstrap/values-bootstrap.yaml
=> 🐪 updated to 1.7 argocd 🐪

argo-app-of-apps.yaml, ubiquitous-journey/values-day2ops.yaml, ubiquitous-journey/values-extratooling.yaml, ubiquitous-journey/values-tooling.yaml
🦀🦀 Fixes sync policy validate causes by upstream doco bug:
https://github.com/argoproj/argo-cd/issues/3208
Also, automates sync for app-of-apps pattern .. this is GitOps after all :) 🦀🦀
=> 🐉 fix sync policy 🐉

example-deployment/values-applications.yaml
update sync policy to work with latest argocd versions
=> 🦢 fix sync options for example app 🦢

README.md, docs/argocd-master-child.md, docs/bootstrap-argocd.md, docs/deploy-custom-namespace.md, docs/whats-in-the-box.md
Tried to come up with a less intimidating welcome page 😅
=> Readme divided into smaller chunks 🔪

README.md, ubiquitous-journey/values-tooling.yaml
add Pelorus
https://github.com/redhat-cop/pelorus
this will also need this to merge for argocd sync to work
https://github.com/redhat-cop/pelorus/pull/135
=> 🐕‍  add pelorus 🐕‍

docs/whats-in-the-box.md, ubiquitous-journey/values-day2ops.yaml
https://github.com/redhat-cop/openshift-management/pull/74 is merged so pointing to CoP repo.
=> ♏ prune jobs points to CoP ♏

ubiquitous-journey/values-tooling.yaml
perlorus changes, x2 charts now
- operator chart
- pelorus chart
deploy to labs-ci-cd namespace
chart directories changed ustream
=> 🐧Feature/fix-pelorus 🐧

ubiquitous-journey/values-tooling.yaml
default some sonarqube plugins language packs we use as well as dep check
=> 🐾 add default plugins we use for sonarqube code analysis - java, js, php 🐾

bootstrap/Chart.yaml
**Issue:**
Failure on pulling dependencies.
sealed-secrets - 
```
$ helm template bootstrap --dependency-update -f bootstrap/values-bootstrap.yaml bootstrap | oc apply -f-
Error: could not download https://kubernetes-charts.storage.googleapis.com/sealed-secrets-1.10.2.tgz: failed to fetch https://kubernetes-charts.storage.googleapis.com/sealed-secrets-1.10.2.tgz : 403 Forbidden
error: error parsing STDIN: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context
```
bootstrap-project - 
```
$ helm template bootstrap --dependency-update -f bootstrap/values-bootstrap.yaml bootstrap | oc apply -f-
error: error parsing STDIN: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
```
**Resolution:**
Updated each of the …
=> fix dependencies of sealed-secrets, argocd-operator, bootstrap-project

README.md
Added `Cleanup` section to README.
Document is very useful and only needed a part where a user can do a cleanup if they wanted.
https://github.com/rht-labs/ubiquitous-journey/issues/206
=> add Cleanup section to README

ubiquitous-journey/values-tooling.yaml
Regarding issue https://github.com/rht-labs/ubiquitous-journey/issues/207, updated the example values for Pelorus.
=> 🐝 Pelorus values updated 🐝

argo-app-of-apps.yaml, docs/whats-in-the-box.md, ubiquitous-journey/values-tooling.yaml
Describe the behavior changes introduced in this PR
This PR add microcks
Linked Issues?
resolver #223 
Testing Instructions
Edit ubiquitous-journey/values-tooling.yaml and change microcks config "enabled" to "true":
- name: microcks
enabled: true
destination: microcks
source: https://github.com/rht-labs/refactored-adventure
source_path: microcks/base
source_ref: master
sync_policy: *sync_policy_true
no_helm: true
Install as usual [](https://github.com/rht-labs/ubiquitous-journey/blob/master/README.md)
=> Add microcks to UJ

ubiquitous-journey/values-tooling.yaml
=> 🌶️ add og for uj bootstrap 🌶️

ubiquitous-journey/values-tooling.yaml
=> 🐀 align latest values in core charts 🐀
